FROM python:3.10-slim

WORKDIR /app

COPY ./backend /app
COPY ./frontend /app  
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy application files and templates folder
COPY . .

CMD ["python", "app.py"]
