apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsexamapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsexamapp
  template:
    metadata:
      labels:
        app: devopsexamapp
    spec:
      containers:
        - name: devopsexamapp
          image: vijaysai1718/devopsexam  # replace with your custom image 
          ports:
            - containerPort: 5000
          env:
           - name: FLASK_APP
             value: app.py
           - name: FLASK_ENV
             value: production
           - name: MYSQL_HOST
             value: mysql 
           - name: MYSQL_USER
             value: root
           - name: MYSQL_PASSWORD
             value: rootpass
           - name: MYSQL_DATABASE
             value: devops_exam
---
apiVersion: v1
kind: Service
metadata:
  name: devopsexamappservice
spec:
  selector:
    app: devopsexamapp
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer  # or ClusterIP if you don't need external access

